#!/bin/sh -e

project="/home/webenmr/WebENMR/"
cd $project

case "$1" in
start)
export PYTHON_EGG_CACHE=/home/webenmr/.python-eggs;/home/webenmr/pyvirt/bin/paster serve --daemon --user apache --group apache --pid-file=paster.pid --log-file=server.log  development.ini start
;;
stop)
/home/webenmr/pyvirt/bin/paster serve --daemon --user apache --group apache --pid-file=paster.pid --log-file=server.log  development.ini stop
;;
restart)
export PYTHON_EGG_CACHE=/home/webenmr/.python-eggs;/home/webenmr/pyvirt//bin/paster serve  --daemon --user apache --group apache --pid-file=paster.pid --log-file=server.log development.ini restart
;;
*)
echo $"Usage: $0 {start|stop|restart}"
exit 1
esac

